name: aimesig_erp
description: Aimesig ERP - Multi-tenant ERP for Schools & Organisations
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.1.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Local Storage / Auth
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3

  # Navigation
  go_router: ^13.2.0

  # UI
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  fl_chart: ^0.67.0
  intl: ^0.19.0
  timeago: ^3.6.1

  # Forms & Validation
  reactive_forms: ^17.0.0

  # Misc
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
