// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8P_eASlAYbsqqR43hJt5cUf8IjeuK_j8',
    appId: '1:229626550217:web:30d05a774b7f0427bafa18',
    messagingSenderId: '229626550217',
    projectId: 'aimesig',
    authDomain: 'aimesig.firebaseapp.com',
    storageBucket: 'aimesig.firebasestorage.app',
    measurementId: 'G-QKWLF7N02R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw3h7nJDTVxrIx2Pz78slzztvmAlp3w2o',
    appId: '1:229626550217:android:42fa211bc0c1a906bafa18',
    messagingSenderId: '229626550217',
    projectId: 'aimesig',
    storageBucket: 'aimesig.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwkvH3WTkIQhR2A3neNsUMA9IQCPnMnlI',
    appId: '1:229626550217:ios:a27202adf4a803ebbafa18',
    messagingSenderId: '229626550217',
    projectId: 'aimesig',
    storageBucket: 'aimesig.firebasestorage.app',
    iosClientId: '229626550217-is68er6rl3ka3kcog4t3oul76kqan106.apps.googleusercontent.com',
    iosBundleId: 'com.example.aimesigFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwkvH3WTkIQhR2A3neNsUMA9IQCPnMnlI',
    appId: '1:229626550217:ios:a27202adf4a803ebbafa18',
    messagingSenderId: '229626550217',
    projectId: 'aimesig',
    storageBucket: 'aimesig.firebasestorage.app',
    iosClientId: '229626550217-is68er6rl3ka3kcog4t3oul76kqan106.apps.googleusercontent.com',
    iosBundleId: 'com.example.aimesigFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8P_eASlAYbsqqR43hJt5cUf8IjeuK_j8',
    appId: '1:229626550217:web:7486c8a914422cffbafa18',
    messagingSenderId: '229626550217',
    projectId: 'aimesig',
    authDomain: 'aimesig.firebaseapp.com',
    storageBucket: 'aimesig.firebasestorage.app',
    measurementId: 'G-WS7V5V6M1M',
  );
}
